---
title: "Cointegration: Gold & Silver"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(quantmod)
library(urca)
```

## Gold Series

```{r}
getSymbols("GC=F",from="2012-01-01",to="2017-12-31")
Gold=na.omit(get("GC=F"))
```


```{r}
chart_Series(Gold)
```



```{r}
serie1=Gold[,6]
plot(serie1)
```


# Augmented Dickey-Fuller test for Gold series

```{r}
summary(ur.df(serie1,selectlags="AIC"))
summary(ur.df(serie1,selectlags="AIC",type="drift"))
summary(ur.df(serie1,selectlags="AIC",type="trend"))
```

# Differenced Gold Series

```{r}
d1serie1=diff(serie1)[-1]
plot(d1serie1)
```

# Augmented Dickey-Fuller test for differenced Gold series

```{r}
summary(ur.df(d1serie1,selectlags="AIC"))
summary(ur.df(d1serie1,selectlags="AIC",type="drift"))
summary(ur.df(d1serie1,selectlags="AIC",type="trend"))
```

## Silver Series

```{r}
getSymbols("SI=F",from="2012-01-01",to="2017-12-31")
Silver=na.omit(get("SI=F"))
```

```{r}
chart_Series(Silver)
```


```{r}
serie2=Silver[,6]
plot(serie2)
```

# Augmented Dickey-Fuller test for Gold series

```{r}
summary(ur.df(serie2,selectlags="AIC"))
summary(ur.df(serie2,selectlags="AIC",type="drift"))
summary(ur.df(serie2,selectlags="AIC",type="trend"))
```

# Differenced Silver series

```{r}
d1serie2=diff(serie2)[-1]
plot(d1serie2)
```

# Augmented Dickey-Fuller test for differenced Silver series

```{r}
summary(ur.df(d1serie2,selectlags="AIC"))
summary(ur.df(d1serie2,selectlags="AIC",type="drift"))
summary(ur.df(d1serie2,selectlags="AIC",type="trend"))
```

# Linear model 

```{r}
g<-serie1
s<-serie2
plot(ts(cbind(g,s)))
```


```{r}
summary(cbind(g,s))
summary(m1<-lm(g~s))
e<-resid(m1)[-length(serie1)]
```
```{r}
plot(resid(m1))
```

```{r}
qqnorm(resid(m1))
qqline(resid(m1))
```
```{r}
acf(resid(m1),ylim=c(-1,1),lag.max=100,lwd=2)
pacf(resid(m1),ylim=c(-1,1),lag.max=100,lwd=2)
```

```{r}
summary(ur.df(resid(m1),selectlags="AIC"))
summary(ur.df(resid(m1),selectlags="AIC",type="drift"))
summary(ur.df(resid(m1),selectlags="AIC",type="trend"))
```

## Error Correction Model


```{r}
dg=d1serie1[-c(1:3)]
dg_1=lag(d1serie1,1)[-c(1:3)]
dg_2=lag(d1serie1,2)[-c(1:3)]
dg_3=lag(d1serie1,3)[-c(1:3)]

ds=d1serie2[-c(1:3)]
ds_1=lag(d1serie2,1)[-c(1:3)]
ds_2=lag(d1serie2,2)[-c(1:3)]
ds_3=lag(d1serie2,3)[-c(1:3)]
er=e[-c(1:3)]
summary(ecm<-step(lm(dg~dg_1+dg_2+dg_3+ds+ds_1+ds_2+ds_3+er)))
```

```{r}
ts.plot(resid(ecm))
```


```{r}
qqnorm(resid(ecm))
qqline(resid(ecm))
```
```{r}
acf(resid(ecm),ylim=c(-1,1),lag.max=100,lwd=2)
pacf(resid(ecm),ylim=c(-1,1),lag.max=100,lwd=2)
```

