---
title: "Conditional Heterocedastic models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(quantmod)
library(fGarch)
library(fBasics)
```

## NASDAQ

```{r}
getSymbols("^IXIC")
val=get("IXIC")
```


```{r}
head(val)
tail(val)
```
```{r}
chartSeries(val)
```

```{r}
serie=val[,6]
plot(serie)
```

## Log-Returns calculation

```{r}
returns=diff(log(serie))[-1]
plot(returns)
```

## Centered Log-Returns

```{r}
t.test(as.vector(returns))
```
```{r}
ret=returns-mean(returns)
```


## Volatility Diagnose

```{r}
plot(ret)
```
```{r}
plot(ret^2)
```
```{r}
par(mfrow=c(1,2))
qqnorm(ret)
qqline(ret,col=2,lwd=2)
hist(ret,probability=TRUE)
curve(dnorm(x,mean=mean(ret),sd=sd(ret)),lwd=2,col=2,add=T)
par(mfrow=c(1,1))
```
```{r}
basicStats(ret)
```

```{r}
par(mfrow=c(1,2))
acf(ret,lwd=2,lag.max=50)
pacf(ret,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

```{r}
par(mfrow=c(1,2))
acf(ret^2,lwd=2,lag.max=50)
pacf(ret^2,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

## Standardized Residuals (Marginal sigma)

```{r}
stres=ret/sd(ret)

llim=xts(rep(-1.96,length(stres)),order.by=index(stres))
ulim=xts(rep(1.96,length(stres)),order.by=index(stres))

plot(ts(stres))
abline(h=c(-2,2),col=4,lty=2,lwd=3)
```

```{r}
basicStats(stres)
```
```{r}
par(mfrow=c(1,2))
qqnorm(stres)
qqline(stres,col=2,lwd=2)
hist(stres,probability=TRUE)
curve(dnorm(x,mean=mean(stres),sd=sd(stres)),lwd=2,col=2,add=T)
par(mfrow=c(1,1))
```

```{r}
par(mfrow=c(1,2))
acf(stres,lwd=2,lag.max=50)
pacf(stres,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

```{r}
par(mfrow=c(1,2))
acf(stres^2,lwd=2,lag.max=50)
pacf(stres^2,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

## ARCH(1)

```{r}
summary(m1<-garchFit(~garch(1,0),returns))
```
```{r}
par(mar=c(3,3,3,1))
tsdiag(m1)
```


```{r}
plot(ts(as.array(ret)))
lines(-1.96*m1@sigma.t,col=4,lty=2,lwd=1)
lines(1.96*m1@sigma.t,col=4,lty=2,lwd=1)
```

```{r}
stres1=ret/m1@sigma.t
plot(ts(stres1))
abline(h=c(-2,2),col=4,lty=2,lwd=3)
```

```{r}
par(mfrow=c(1,2))
qqnorm(stres1)
qqline(stres1,col=2,lwd=2)
hist(stres1,probability=TRUE)
curve(dnorm(x,mean=mean(stres1),sd=sd(stres1)),lwd=2,col=2,add=T)
par(mfrow=c(1,1))
```
```{r}
basicStats(stres1)
```

```{r}
par(mfrow=c(1,2))
acf(stres1,lwd=2,lag.max=50)
pacf(stres1,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

```{r}
par(mfrow=c(1,2))
acf(stres1^2,lwd=2,lag.max=50)
pacf(stres1^2,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

## ARCH(6)

```{r}
summary(m2<-garchFit(~garch(6,0),returns))
```
```{r}
par(mar=c(3,3,3,1))
tsdiag(m2)
```

```{r}
plot(ts(as.array(ret)))
lines(-1.96*m2@sigma.t,col=4,lty=2,lwd=1)
lines(1.96*m2@sigma.t,col=4,lty=2,lwd=1)
```
```{r}
stres2=ret/m2@sigma.t
plot(ts(stres2))
abline(h=c(-2,2),col=4,lty=2,lwd=3)
```

```{r}
par(mfrow=c(1,2))
qqnorm(stres2)
qqline(stres2,col=2,lwd=2)
hist(stres2,probability=TRUE)
curve(dnorm(x,mean=mean(stres2),sd=sd(stres2)),lwd=2,col=2,add=T)
par(mfrow=c(1,1))
```
```{r}
basicStats(stres2)
```
```{r}
par(mfrow=c(1,2))
acf(stres2,lwd=2,lag.max=50)
pacf(stres2,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

```{r}
par(mfrow=c(1,2))
acf(stres2^2,lwd=2,lag.max=50)
pacf(stres2^2,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

## GARCH(1,1)

```{r}
summary(m3<-garchFit(~garch(1,1),returns))
```
```{r}
par(mar=c(3,3,3,1))
tsdiag(m3)
```

```{r}
plot(ts(as.array(ret)))
lines(-1.96*m3@sigma.t,col=4,lty=2,lwd=1)
lines(1.96*m3@sigma.t,col=4,lty=2,lwd=1)
```

```{r}
stres3=ret/m3@sigma.t
plot(ts(stres3))
abline(h=c(-2,2),col=4,lty=2,lwd=3)
```
```{r}
par(mfrow=c(1,2))
qqnorm(stres3)
qqline(stres3,col=2,lwd=2)
hist(stres3,probability=TRUE)
curve(dnorm(x,mean=mean(stres3),sd=sd(stres3)),lwd=2,col=2,add=T)
par(mfrow=c(1,1))
```
```{r}
basicStats(stres3)
```


```{r}
par(mfrow=c(1,2))
acf(stres3,lwd=2,lag.max=50)
pacf(stres3,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```

```{r}
par(mfrow=c(1,2))
acf(stres3^2,lwd=2,lag.max=50)
pacf(stres3^2,lwd=2,lag.max=50)
par(mfrow=c(1,1))
```


